#!/bin/bash

pycheck(){
if pip list | grep "${1}" 1> /dev/null ; then
    echo "'$ pip ${1}' found, skipping installing..."
else
    echo "'$ pip ${1}' not found, installing ${1}..."
    pip3 install "${1}"
fi
}

if command -v "pip3" 1> /dev/null ; then
    echo "'$ pip3' found, skipping installing..."
else
    echo "'$ pip3' not found, installing pip..."
    sudo apt install pip3
fi

pycheck "pygame"
pycheck "sys"
pycheck "random2"
pycheck "tk"

echo "All dependencies were checked, do you want to run the script ? (y/n)"
read -r answer
if [ "${answer,,}" == "n" ] || [ "${answer,,}" == "no" ]; then
    exit 0;
fi

exec ./Mort-d-or.py
